---
Name: testdata_routes
---
Director:
  rules:
    'dev/data/export//$Action/$ID/$OtherID': 'TestDataExporter'
    'dev/data/TestDataExporter//$Action/$ID/$OtherID': 'TestDataExporter'
    'dev/data//$Action/$ID/$OtherID':  'TestDataController'
